services:
  listmonk:
    build: .
    depends_on:
      - postgres
    ports:
      - 9000:9000
  postgres:
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres:16.3-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: null
