# https://fly.io/docs/reference/configuration/

app = 'haskellweekly-listmonk'
primary_region = 'dfw'

[build]

[env]
  LISTMONK_app__address = "0.0.0.0:8080"
  # LISTMONK_app__admin_password = ""
  LISTMONK_app__admin_username = "listmonk"
  LISTMONK_db__database = "haskellweekly_listmonk"
  LISTMONK_db__host = "haskellweekly-postgres.flycast"
  # LISTMONK_db__password = ""
  LISTMONK_db__port = "5432"
  LISTMONK_db__ssl_mode = "disable"
  LISTMONK_db__user = "haskellweekly_listmonk"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
